### ISSUE TITLE
No converter found capable of converting from type [dev.miku.r2dbc.mysql.codec.lob.SingletonClob] to type [java.lang.String]

### ISSUE THREAD

**Issue by xuechaoke** [mirromutth/r2dbc-mysql#106]
sql  :
SELECT
	GROUP_CONCAT( DISTINCT g.id ) AS id,
	GROUP_CONCAT( DISTINCT g.gateway_flag ) AS gateway_flag,
	GROUP_CONCAT( DISTINCT gsb.bank_id ) AS bank_id,
	GROUP_CONCAT( DISTINCT g.state ) AS state 
FROM
	pay_gateway_support_bank AS gsb
	LEFT JOIN pay_gateway AS g ON g.id = gsb.gateway_id 
WHERE
	g.state = 1 
	AND g.del_flag = 0 
GROUP BY
	gsb.gateway_id

![2ac14e0fd4b09a49291b9f500118700](https://user-images.githubusercontent.com/37655156/76609680-bd8bc980-6552-11ea-89d8-eea39dafaf5e.png)

Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [dev.miku.r2dbc.mysql.codec.lob.SingletonClob] to type [java.lang.String]
	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:321)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:194)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:174)
	at org.springframework.data.r2dbc.convert.MappingR2dbcConverter.getPotentiallyConvertedSimpleRead(MappingR2dbcConverter.java:198)
	at org.springframework.data.r2dbc.convert.MappingR2dbcConverter.readFrom(MappingR2dbcConverter.java:167)
	... 64 common frames omitted

**Comment by mirromutth** [comment]
Hi there, thanks for the report, sorry for my late reply.

Which `r2dbc-mysql` version are you using? For latest GA version, this should not happen.

Thanks for your time.

**Comment by xuechaoke** [comment]
which&nbsp;&nbsp;maven repository&nbsp; can i get&nbsp;latest GA version ? i cant find id&nbsp; on&nbsp;https://mvnrepository.com/




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mirro Mutth"<notifications@github.com&gt;; 
发送时间: 2020年3月18日(星期三) 下午3:31
收件人: "mirromutth/r2dbc-mysql"<r2dbc-mysql@noreply.github.com&gt;; 
抄送: "粮食与思想"<121960452@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mirromutth/r2dbc-mysql] No converter found capable of converting from type [dev.miku.r2dbc.mysql.codec.lob.SingletonClob] to type [java.lang.String] (#106)





 
Hi there, thanks for the report, sorry for my late reply.
 
Which r2dbc-mysql version are you using? For latest GA version, this should not happen.
 
Thanks for your time.

**Comment by mirromutth** [comment]
Yes, it is. Try using `r2dbc-mysql:0.8.1.RELEASE` and `spring-data-r2dbc:1.0.0.RELEASE`.

Before `0.8.0.RELEASE`, by default, when MySQL type was" TEXT ", the driver would return" Clob ".

See [0.8.0.RELEASE CHANGELOG](https://github.com/mirromutth/r2dbc-mysql/blob/master/CHANGELOG.md#features-change-1)

**Comment by mirromutth** [comment]
Hi @xuechaoke, is the problem solved? This question will be closed in 3 days

**Comment by mirromutth** [comment]
I'm closing it due to inactivity.
