### ISSUE TITLE
ON DUPLICATE KEY UPDATE statement not work

### ISSUE THREAD

**Issue by rolandblain** [mirromutth/r2dbc-mysql#156]
hi.
I'm using spring data + webflux + j2dbc-mysql stack and schema is as follow

```sql
CREATE TABLE `deposit` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `balance` double NOT NULL DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `deposit_userid` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=latin1;
```

and here is a repository code

```kotlin
import org.springframework.data.r2dbc.repository.Modifying
import org.springframework.data.r2dbc.repository.Query
import org.springframework.data.repository.reactive.ReactiveCrudRepository
import org.springframework.stereotype.Repository
import reactor.core.publisher.Mono

@Repository
interface DepositRepository : ReactiveCrudRepository<Deposit, Long> {

    @Query("SELECT * FROM deposit WHERE deposit.user_id = :userId")
    fun findByUserId(userId: Long): Mono<Deposit>

    @Query("INSERT INTO deposit(user_id, balance) VALUES (:user_id, :quantity) ON DUPLICATE KEY UPDATE balance = balance + :quantity")
    fun upsertBalance(userId: Long, quantity: Double): Mono<Long>
}
```

while executing following test code,

```kotlin
    @Test
    fun testUpsert() {
        val deposit = depositRepository.save(Deposit(null, 1L, 2.5, Instant.now(), Instant.now()))
            .flatMap {
                depositRepository.upsertBalance(1L, 3.0)
                    .flatMap {
                        depositRepository.findByUserId(1L)
                    }
            }
            .block()

        assertEquals(5.5, deposit.balance)
    }
```

i'm getting this error

```
org.springframework.dao.DataIntegrityViolationException: executeMany; SQL [INSERT INTO deposit (user_id, balance, created_at, updated_at) VALUES (?, ?, ?, ?)]; Duplicate entry '1' for key 'deposit_userid'; nested exception is io.r2dbc.spi.R2dbcDataIntegrityViolationException: [1062] [23000] Duplicate entry '1' for key 'deposit_userid'

	at org.springframework.data.r2dbc.support.R2dbcExceptionSubclassTranslator.doTranslate(R2dbcExceptionSubclassTranslator.java:78)
	at org.springframework.data.r2dbc.support.AbstractFallbackR2dbcExceptionTranslator.translate(AbstractFallbackR2dbcExceptionTranslator.java:67)
	at org.springframework.data.r2dbc.core.DefaultDatabaseClient.translateException(DefaultDatabaseClient.java:264)
	at org.springframework.data.r2dbc.core.DefaultDatabaseClient.lambda$inConnectionMany$8(DefaultDatabaseClient.java:200)
	at reactor.core.publisher.Flux.lambda$onErrorMap$29(Flux.java:6539)
	at reactor.core.publisher.Flux.lambda$onErrorResume$30(Flux.java:6592)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.deferredError(FluxUsingWhen.java:408)
	at reactor.core.publisher.FluxUsingWhen$RollbackInner.onComplete(FluxUsingWhen.java:485)
...
```

It will be a pleasant if you let me know whether it is r2dbc-mysql problem or not.

Have a nice day and thanks in advance!! ^.^

**Comment by mirromutth** [comment]
Hi there,

I have created a PR for add a test case for `INSERT ON DUPLICATE KEY UPDATE` statement, and it seems work well.

Could you please let me know more details regarding this? Like Spring Data R2DBC version and `r2dbc-mysql` version.

I pasted the following code for the demo, and it works well:

```java
@RestController
@SpringBootApplication
@EnableR2dbcRepositories
public class DemoApplication {
    
    private final TestRepository repository;

    public DemoApplication(TestRepository repository) {
        this.repository = repository;
    }

    @GetMapping
    public Mono<TestEntity> upsert() {
        return repository.upsertValue(1, 10)
            .then(repository.findById(1));
    }

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }
}

/**
 * CREATE TABLE test(id INT PRIMARY KEY,value INT NOT NULL)
 */
@lombok.Data
@Table("test")
class TestEntity {

    @Id
    @Column("id")
    private Integer id;

    @Column("value")
    private Integer value;
}

interface TestRepository extends ReactiveCrudRepository<TestEntity, Integer> {

    @Query("INSERT INTO test VALUES (:id, :value) ON DUPLICATE KEY UPDATE value = value + :value")
    Mono<Integer> upsertValue(int id, int value);
}
```

In my demo, `spring-boot-starter-parent` version (also `spring-boot-starter-data-r2dbc` version) is `2.4.1`, `r2dbc-mysql` version is `0.8.2.RELEASE`.

Have a nice day too.

**Comment by rolandblain** [comment]
SORRY IT WAS MY SPELL ERROR!! orz
Very very thanks.. you very kind!
Happy christmas and happy new year!
